### ISSUE TITLE
Just after install it

### ISSUE THREAD

**Issue by josuevalrob** [gabesullice/jwt#21]
After tried to go to /admin/config/system/jwt i got this: _The website encountered an unexpected error. Please try again later._

In the console log: _Failed to load resource: the server responded with a status of 500 (500 Service unavailable (with message))_

And, in the php error log this:
`[Sat Mar 17 12:17:53.069028 2018] [fcgid:warn] [pid 56344:tid 3031629824] [client 127.0.0.1:62217] mod_fcgid: stderr: Uncaught PHP Exception InvalidArgumentException: "Class "\\Drupal\\jwt\\Form\\ConfigForm" does not exist." at /Users/josue/WebDevelop/angudru/drupal/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php line 24, referer: http://angudru.dd:8083/admin/modules`

**Comment by ebremer** [comment]
@josuevalrob how did you install JWT?  I ran into similar issues when I DIDN'T use composer.  Once I did my installs with composer, it worked fine.

**Comment by josuevalrob** [comment]
@ebremer sorry, I didnt use this module. 
But I wrote multiple bogs about how to do json web token with drupal + angular, maybe that could help you
[my blog](https://josuevalrob.com/article/angudru)
