### ISSUE TITLE
How to get the User token after login. 

### ISSUE THREAD

**Issue by josuevalrob** [gabesullice/jwt#22]
After enabling the JWT module, and following this [tutorial](https://www.mediacurrent.com/blog/using-json-web-tokens-jwt-authenticate-requests-rest-resources-drupal-8/) about how to use it, is working.

I know that I can access the user JWT token by going to: /jwt/token.

My problem is when I try to login via web services. It shows me this:

{
    "current_user": {
        "uid": "4",
        "name": "cravushedal"
    },
    "csrf_token": "OlTb7fak5ZS-r1BRiGtBh4IWLm_Z7F1xMpY3KYTGkrU",
    "logout_token": "5DiupHgr9iDxIDVmhHTI3PMX2-Shd6sjuN8hNHrHv7E"
}
No JWT token. What can I do to debug this?

**Comment by jongirard** [comment]
Were you able to solve this? I'm having the same problem @josuevalrob
