### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by ebremer** [gabesullice/jwt#25]

**Comment by pwolanin** [comment]
Look on drupal.org for any new work

https://www.drupal.org/project/jwt

**Comment by sun** [comment]
The d.o project page refers to this GitHub repo for all development work though…?

**Comment by ebremer** [comment]
Yes, the project page points here which is why I asked the question here...

![jwt](https://user-images.githubusercontent.com/4094961/47432752-f0ba9680-d76c-11e8-88d6-fbbee5a919dd.jpg)

**Comment by pwolanin** [comment]
Gabe made me a maintainer on d.o, but I haven't had time to work on things yet.  Is there a particular issue?

**Comment by ebremer** [comment]
It's a great module and I have been spending time understanding the code in detail.  I just wanted to make sure it was still an active project.  I do have a question that came up yesterday, but I will ask it as a separate comment.
